"use client";

import React, { useState, useEffect } from "react";
import { Sparkles } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Card, CardContent } from "@/components/ui/card";
import { getAISummary } from "@/lib/api";

interface AIProductSummaryProps {
  productId: string;
}

export default function AIProductSummary({ productId }: AIProductSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    getAISummary(productId).then((res) => {
      if (!cancelled) {
        setSummary(res.summary ?? null);
        setLoading(false);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [productId]);

  if (loading) {
    return (
      <div className="my-6 space-y-2">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-indigo-400" />
          <span className="text-sm font-medium text-slate-600 dark:text-slate-400">
            Generating AI analysis...
          </span>
        </div>
        <Skeleton className="h-24 w-full rounded-lg" />
      </div>
    );
  }

  if (!summary) return null;

  return (
    <Card className="my-6 border-indigo-500/20 bg-indigo-500/5 dark:bg-indigo-500/5">
      <CardContent className="p-5">
        <div className="mb-3 flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-indigo-400" />
          <span className="text-sm font-semibold text-slate-900 dark:text-slate-100">
            SmartBuy AI Analysis
          </span>
        </div>
        <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
          {summary}
        </p>
        <div className="mt-3 border-t border-indigo-500/10 pt-2">
          <span className="text-xs text-slate-500">
            🤖 Generated by SmartBuy AI
          </span>
        </div>
      </CardContent>
    </Card>
  );
}
